### ISSUE TITLE
Uses legacy 'node' 

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/ddg-screen-diff#10]
Using `npm install ddg-screen-diff` isn't enough - by [this post](https://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu) you need to install `nodejs-legacy` first.

Maybe this should be in docs (or if possible, fixed)?

**Comment by andrey-p** [comment]
Hey @GuiltyDolphin thanks for reporting! I'll add a mention of this to the docs - the `nodejs-legacy` thing is only required in Debian/Ubuntu, and it depends on the way you install it (I think).

As I said, let me know if you bump into anything else!
